services:
  keycloak:
    image: quay.io/keycloak/keycloak:25.0
    restart: unless-stopped
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
    #      KC_HOSTNAME: keycloak
    #      KC_HTTP_RELATIVE_PATH: /kc
    ports:
      - "9080:8080"
    command: start-dev --hostname-strict=false
    networks:
      - local_network

networks:
  local_network:
    external: true
