version: '3.8'
services:
  postgres:
    image: postgis/postgis:16-3.4
    # image: postgres:16
    restart: unless-stopped
    shm_size: 2g
    environment:
      - POSTGRES_PASSWORD=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      # - ./init:/docker-entrypoint-initdb.d
    networks:
      - local_network

networks:
  local_network:
    external: true
